// Generated by CoffeeScript 2.4.1
// Fake snowflake to interact with
var snowflake;

snowflake = {
  ui: new UI,
  broker: {
    sendAnswer: function() {}
  },
  state: Snowflake.MODE.INIT
};

describe('Init', function() {
  it('gives a dialog when closing, only while active', function() {
    var msg, silenceNotifications;
    silenceNotifications = false;
    snowflake.state = Snowflake.MODE.WEBRTC_READY;
    msg = window.onbeforeunload();
    expect(snowflake.state).toBe(Snowflake.MODE.WEBRTC_READY);
    expect(msg).toBe(Snowflake.MESSAGE.CONFIRMATION);
    snowflake.state = Snowflake.MODE.INIT;
    msg = window.onbeforeunload();
    expect(snowflake.state).toBe(Snowflake.MODE.INIT);
    return expect(msg).toBe(null);
  });
  return it('does not give a dialog when silent flag is on', function() {
    var msg, silenceNotifications;
    silenceNotifications = true;
    snowflake.state = Snowflake.MODE.WEBRTC_READY;
    msg = window.onbeforeunload();
    expect(snowflake.state).toBe(Snowflake.MODE.WEBRTC_READY);
    return expect(msg).toBe(null);
  });
});
