fs = require 'fs'

{exec} = require 'child_process'

task 'test', 'snowflake unit tests', () ->
  testFile = 'test/snowflake.bundle.coffee'
  exec 'cat snowflake.coffee snowflake_test.coffee | cat > ' + testFile, (err, stdout, stderr) ->
    throw err if err
    console.log stdout + stderr
  exec 'coffee ' + testFile + ' -v', (err, stdout, stderr) ->
    throw err if err
    console.log stdout + stderr
