// Generated by CoffeeScript 2.4.1
/*
Entry point.
*/
var broker, config, dbg, log, snowflake, ui;

config = new Config;

ui = new UI();

broker = new Broker(config.brokerUrl);

snowflake = new Snowflake(config, ui, broker);

log = function(msg) {
  return console.log('Snowflake: ' + msg);
};

dbg = log;

log('== snowflake proxy ==');

dbg('Contacting Broker at ' + broker.url);

snowflake.setRelayAddr(config.relayAddr);

snowflake.beginWebRTC();
